version: '3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USEDR:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-zSQYFrowY6EwCory}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./db/log/data:/var/lib/postgresql/data
      - ./db/log:/var/log
      - ./db/migration/schema/ :/docker-entrypoint-initdb.d/
    command: postgres -c log_statement=all
    tty: true
  
  api:
    container_name: api
    depends_on: 
      - postgres
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - GOPATH=/go
    ports:
      - 8080:8080
      - 80:80
    tty: true
