version: '3'
services: 
    go:
        build: 
            context: .
            dockerfile: DockerFile
        stdin_open: true
        tty: true
        volumes: 
            - .:/home/app
        ports: 
            - 80:80
    db:
        image: mysql:8.0
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keep_cards
            MYSQL_USER: shiho
            MYSQL_PASSWORD: Nr5kThXz
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306